export const strings = {
  appName: 'Jewel Factory',
  appSubName: '',
  login: 'Log In',
  welcome: 'Welcome to',
  to: 'To',
  mobileNo: 'Mobile Number',
  password: 'Password',
  email: 'Email ID',
  name: 'Name',
  company: 'Company name',
  forgotPassText: 'Forgot password?',
  forgotPassLink: 'Get Help',
  dontHaveAccount: "Don't have an account? ",
  register: 'Register',
  newPassword: 'New Password',
  conformPassword: 'Confirm new password',
  next: "Next",
  invalidEmail: 'Please enter correct email',
  invalidPassword:
    'Password must be atleast six character long, contain one special character and one numeric',
  globalErrorMsg: 'Something went wrong',
  serverFailedMsg:
    'We are unable to connect at this moment.\nPlease try again later.',
  categoryDesigns: 'Category',
  seeMore: 'More',
  latestDesigns: 'Latest',
  bestSelling: 'Best',
  diwaliCollection: 'Diwali Collection',
  submit: 'Submit',
  scannedCodePH: 'Code you have scanned will appear here..',
  close: 'close',
  aboutUs: 'About us',
  privacyPolicy: 'Privacy policy',
  termsCondition: 'Terms & conditions',
  logout: 'Log out',
  customOrder: 'Custom order',
  share: 'Share',
  exclusive: 'Exclusive',
  orderHistory: 'Order history',
  connectWithUs: 'Connect with us',
  deleteAccount: 'Delete account',
  rateUs: 'Rate us',
  edit: 'Edit',
  version: 'Version:',
  madeWithLove: 'Made with ❤️ by',
  muskseed: 'Muskseed',
  explore: 'Explore',
  shareApp: 'Share app',
  rateApp: 'Rate app',
  categories: "Categories"
};
