export const strings = {
  appName: 'Jewel Factory',
  appSubName: '',
  login: 'Log In',
  welcome: 'Welcome to',
  to: 'To',
  mobileNo: 'Mobile Number',
  password: 'Password',
  email: 'Email ID',
  name: 'Name',
  company: 'Company name',
  forgotPassText: 'Forgot password?',
  forgotPassLink: 'Get Help',
  dontHaveAccount: "Don't have an account? ",
  register: 'Register',
  newPassword: 'New Password',
  conformPassword: 'Confirm new password',
  next: "Next",
  invalidEmail: 'Please enter correct email',
  invalidPassword:
    'Password must be atleast six character long, contain one special character and one numeric',
  globalErrorMsg: 'Something went wrong',
  serverFailedMsg:
    'We are unable to connect at this moment.\nPlease try again later.',
  categoryDesigns: 'Category',
  seeMore: 'More',
  latestDesigns: 'Latest',
  bestSelling: 'Best',
  diwaliCollection: 'Diwali Collection',
  submit: 'Submit',
  scannedCodePH: 'Code you have scanned will appear here..',
  close: 'close',
  aboutUs: 'About us',
  privacyPolicy: 'Privacy policy',
  termsCondition: 'Terms & conditions',
  logout: 'Log out',
  customOrder: 'Custom order',
  share: 'Share',
  exclusive: 'Exclusive',
  orderHistory: 'Order history',
  connectWithUs: 'Connect with us',
  deleteAccount: 'Delete account',
  rateUs: 'Rate us',
  edit: 'Edit',
  version: 'Version:',
  madeWithLove: 'Made with ❤️ by',
  muskseed: 'Muskseed',
  explore: 'Explore',
  shareApp: 'Share app',
  rateApp: 'Rate app',
  categories: "Categories",
  filter: 'Filter',
  filterDesc: 'Filter products by Gross weight, Net weight etc',
  sort: 'Sort',
  viewAs: 'View as',
  viewAsDesc: 'View products in different mode like grid,single etc\n(arrow indicates scroll direction)',
  productsFound: 'products found',
  enterMobileNo: 'Please enter mobile number',
  enterValidMobileNo: 'Please enter valid mobile number',
  enterPassword: 'Please enter password',
  defaultToastText1: 'Oops',
  defaultToastText2: 'Something went wrong',
  enterName: 'Please enter full name',
  enterEmail: 'Please enter email address',
  enterValidEmail: 'Please enter valid email address',
  enterValidPassword: 'Password must be atleast 4 character long',
  verifyMobileNo: 'Verify your Mobile Number',
  enterOtpSentTo: 'Please enter OTP sent to ******',
  enterOtp: 'Please enter OTP',
  enterValidOtp: 'Please enter valid OTP',
  resendOtp: 'Resend OTP',
  getOtp: 'Get OTP',
  resetYourPasswordHere: 'Reset your password here',
  enterRegisteredMobileNo: 'Enter the mobile number associated\nwith your account',
  coming_soon_title: 'Coming Soon!!',
  coming_soon_subtitle:
    'Like all good things, this feature will take some time to be live.',
  noDataFound: 'No data found',
  alreadyAddedToWishlist: 'Product already added to wishlist',
  code: "Code",
  collection: 'Collection',
  moreDetails: 'More Details',
  moveToWishlist: 'Move to wishlist',
  delete: 'Delete',
  cart: 'cart',
  wishlist: 'wishlist',
  cartSummary: 'Cart Summary',
  cartWeightDesc: 'Find the details about products here',
  placeOrder: 'Place Order',
  confirmOrder: "Confirm your order",
  placeOrderSubtitle: "Make sure everything looks good\nand hit 'Place Order' to finish.",
  contactUs: 'Contact Us',
  contactUsDesc: "Connect with us if you are facing any issues.\nWe are happy to help you.",
  whatsapp: 'Whatsapp',
  callUs: 'Call Us',
  totalWeight: 'Total Weight',
  totalQuantity: "Total Quantity",
  grossWt: 'Gross Wt',
  netWt: 'Net Wt',
  quantity: 'Quantity',
  designNo: 'Design No',
  comments: 'Comments',
  deliveryDateMsg: 'Please select delivery date next to 12 days',
  sortBy: "Sort by",
  sortByDesc: "See products here by ascending or descending order",
  apply: 'Apply',
  addToCart: 'Add to Cart',
  addToWishlist: 'Add to Wishlist',
  remark: 'Remark',
  productDesc: 'Product Description',
  customizableDetails: 'Customizable Details'
  ////
  ///
};
